<?php

/**
 * This is the model base class for the table "producto".
 * DO NOT MODIFY THIS FILE! It is automatically generated by AweCrud.
 * If any changes are necessary, you must set or override the required
 * property or method in class "Producto".
 *
 * Columns in table "producto" available as properties of the model,
 * followed by relations of table "producto" available as properties of the model.
 *
 * @property integer $id
 * @property integer $categoria_id
 * @property string $nombre
 * @property string $marca
 *
 * @property Categoria $categoria
 */
abstract class BaseProducto extends AweActiveRecord {

    public static function model($className=__CLASS__) {
        return parent::model($className);
    }

    public function tableName() {
        return 'producto';
    }

    public static function representingColumn() {
        return 'nombre';
    }

    public function rules() {
        return array(
            array('categoria_id, nombre, marca', 'required'),
            array('categoria_id', 'numerical', 'integerOnly'=>true),
            array('nombre, marca', 'length', 'max'=>255),
            array('nombre, marca', 'default', 'setOnEmpty' => true, 'value' => null),
            array('id, categoria_id, nombre, marca', 'safe', 'on'=>'search'),
        );
    }

    public function relations() {
        return array(
            'categoria' => array(self::BELONGS_TO, 'Categoria', 'categoria_id'),
        );
    }

    /**
     * @return array customized attribute labels (name=>label)
     */
    public function attributeLabels() {
        return array(
                'id' => Yii::t('app', 'ID'),
                'categoria_id' => Yii::t('app', 'Categoria'),
                'nombre' => Yii::t('app', 'Nombre'),
                'marca' => Yii::t('app', 'Marca'),
                'categoria' => null,
        );
    }

    public function search() {
        $criteria = new CDbCriteria;

        $criteria->compare('id', $this->id);
        $criteria->compare('categoria_id', $this->categoria_id);
        $criteria->compare('nombre', $this->nombre, true);
        $criteria->compare('marca', $this->marca, true);

        return new CActiveDataProvider($this, array(
            'criteria' => $criteria,
        ));
    }

    public function behaviors() {
        return array_merge(array(
        ), parent::behaviors());
    }
}